### ISSUE TITLE
resthub.org is down

### ISSUE THREAD

**Issue by nitinsurana** [resthub/resthub.github.io#6]

**Comment by bmeurant** [comment]
Hi,

Thanks for reporting.

As Resthub is no more actively maintained, we did not renew the resthub.org domain. I just removed CNAME to make resthub.github.org available but it could take some time.

Links are also broken because of jekyll 3. I try to take a look ASAP.

**Comment by bmeurant** [comment]
Links should be fixed now. There is stille some css issues but you can browse documentation at http://resthub.github.io/
